const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("worktrace", {
  getSettings: () => ipcRenderer.invoke("settings:get"),
  chooseLibrary: () => ipcRenderer.invoke("settings:chooseLibrary"),
  saveSettings: (input) => ipcRenderer.invoke("settings:save", input),
  exportBackup: () => ipcRenderer.invoke("workspace:exportBackup"),
  importBackup: () => ipcRenderer.invoke("workspace:importBackup"),
  createProject: (input) => ipcRenderer.invoke("projects:create", input),
  saveProjects: (projects) => ipcRenderer.invoke("projects:save", projects),
  saveProjectLayout: (input) => ipcRenderer.invoke("projects:saveLayout", input),
  getProjectOverview: (projectId) => ipcRenderer.invoke("projects:getOverview", projectId),
  generateProjectOverview: (projectId) => ipcRenderer.invoke("projects:generateOverview", projectId),
  generateReport: (input) => ipcRenderer.invoke("reports:generate", input),
  chat: (history, context = {}) => ipcRenderer.invoke("ai:chat", { history, context }),
  listTasks: () => ipcRenderer.invoke("tasks:list"),
  reorderTasks: (input) => ipcRenderer.invoke("tasks:reorder", input),
  createTask: (input) => ipcRenderer.invoke("tasks:create", input),
  updateTask: (input) => ipcRenderer.invoke("tasks:update", input),
  deleteTask: (id) => ipcRenderer.invoke("tasks:delete", id),
  openExternal: (url) => ipcRenderer.invoke("app:openExternal", url),
  testAi: (input) => ipcRenderer.invoke("ai:test", input),
  chooseFiles: () => ipcRenderer.invoke("archive:chooseFiles"),
  importFiles: (paths, supplementalText = "", projectId = "") => ipcRenderer.invoke("archive:import", { filePaths: paths, supplementalText, projectId }),
  selftestTools: () => ipcRenderer.invoke("ai:selftestTools"),
  createTextRecord: (text) => ipcRenderer.invoke("archive:createText", text),
  createOfficeFile: (input) => ipcRenderer.invoke("archive:createOfficeFile", input),
  refreshRecord: (id) => ipcRenderer.invoke("archive:refreshRecord", id),
  listRecords: () => ipcRenderer.invoke("archive:list"),
  updateRecord: (input) => ipcRenderer.invoke("archive:updateRecord", input),
  deleteRecord: (input) => ipcRenderer.invoke("archive:deleteRecord", input),
  revealFile: (path) => ipcRenderer.invoke("archive:reveal", path),
  openFile: (path) => ipcRenderer.invoke("archive:open", path),
  pathForFile: (file) => webUtils.getPathForFile(file),
  onProgress: (callback) => ipcRenderer.on("archive:progress", (_event, value) => callback(value)),
  onLibraryChanged: (callback) => ipcRenderer.on("library:changed", (_event, value) => callback(value)),
  onShowTasks: (callback) => ipcRenderer.on("tasks:show", () => callback()),
  agentAvailable: () => ipcRenderer.invoke("agent:available"),
  agentSend: (text) => ipcRenderer.invoke("agent:send", text),
  agentReset: () => ipcRenderer.invoke("agent:reset"),
  onAgentEvent: (callback) => ipcRenderer.on("agent:event", (_event, value) => callback(value)),
  openOrderAssistant: () => ipcRenderer.invoke("order:open"),
  orderSources: () => ipcRenderer.invoke("order:sources"),
  orderInspect: (input) => ipcRenderer.invoke("order:inspect", input),
  orderGenerate: (input) => ipcRenderer.invoke("order:generate", input),
});
